In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4]

In [3]:
type(l)

list

In [4]:
a= np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a1 = np.array([1,2,3,4])

In [8]:
a1

array([1, 2, 3, 4])

In [9]:
a2 = np.array([[1,2,3],[4,5,6]])

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [13]:
a1

array([1, 2, 3, 4])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
a1.ndim

1

In [17]:
a2.ndim

2

In [18]:
a3.ndim

3

In [19]:
l = [1,2,3,4]

In [20]:
np.array(l)

array([1, 2, 3, 4])

In [25]:
a = np.asarray(l)
a

array([1, 2, 3, 4])

In [26]:
m = np.matrix(l)
m

matrix([[1, 2, 3, 4]])

In [29]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [31]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [32]:
a

array([1, 2, 3, 4])

In [33]:
a1 = a

In [35]:
a[0] = 10

In [36]:
a

array([10,  2,  3,  4])

In [37]:
a1

array([10,  2,  3,  4])

In [38]:
a1[0] = 5

In [39]:
a1

array([5, 2, 3, 4])

In [40]:
a

array([5, 2, 3, 4])

In [41]:
a2 = np.copy(a)

In [42]:
a2

array([5, 2, 3, 4])

In [44]:
a[2] = 30

In [46]:
a

array([ 5,  2, 30,  4])

In [47]:
a2

array([5, 2, 3, 4])

In [49]:
np.fromfunction(lambda i,j:i==j,(3,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [56]:
np.random.rand(3,4,5)

array([[[0.96672302, 0.33946352, 0.81574957, 0.63462274, 0.7838278 ],
        [0.746379  , 0.03878678, 0.63940491, 0.58419312, 0.91985391],
        [0.82278471, 0.14637003, 0.13722093, 0.06717967, 0.18584386],
        [0.27753452, 0.79966072, 0.39886688, 0.91686446, 0.51697132]],

       [[0.03406406, 0.18720449, 0.26403928, 0.71838679, 0.27470643],
        [0.42424021, 0.15345992, 0.95263972, 0.25262037, 0.89539428],
        [0.86500921, 0.16668076, 0.73428113, 0.68431017, 0.10508286],
        [0.43148034, 0.66525442, 0.69860064, 0.6264907 , 0.07820103]],

       [[0.92814401, 0.37743593, 0.76239754, 0.09347983, 0.42334016],
        [0.19938943, 0.5247217 , 0.39364099, 0.9100093 , 0.66051809],
        [0.39660302, 0.07798798, 0.4060445 , 0.68368191, 0.69303423],
        [0.80366063, 0.54723514, 0.39311741, 0.98885614, 0.55613366]]])

In [57]:
np.random.rand(2,3,2,2)

array([[[[0.95936441, 0.45767211],
         [0.18838952, 0.74493737]],

        [[0.6046515 , 0.83336067],
         [0.35836085, 0.63649386]],

        [[0.18445899, 0.41798932],
         [0.53708796, 0.27649811]]],


       [[[0.07206027, 0.43464186],
         [0.35896406, 0.54587183]],

        [[0.60065065, 0.34324509],
         [0.65682119, 0.43372518]],

        [[0.96318026, 0.14842406],
         [0.78613052, 0.52796589]]]])

In [59]:
np.random.randint(0,10,(4,2,3))

array([[[2, 8, 6],
        [1, 9, 5]],

       [[8, 3, 9],
        [6, 7, 3]],

       [[9, 2, 6],
        [5, 4, 1]],

       [[8, 4, 7],
        [1, 0, 2]]])

In [61]:
np.random.randn(2,4,3)

array([[[-1.5225394 ,  0.82570403, -0.03226907],
        [-0.1848215 , -2.25057183,  0.02820591],
        [-0.12693251,  0.69155195, -0.71834214],
        [ 2.04012531, -0.49907025,  0.30654272]],

       [[ 1.67366026,  0.6213858 ,  1.74655787],
        [ 0.03332792, -1.29659946,  0.65428328],
        [ 0.72834096,  1.2327497 , -1.18693494],
        [-0.01890492, -1.36805681,  0.59013187]]])

In [63]:
d = np.random.randn(4,3)

In [64]:
d

array([[-0.21778223, -0.1865107 , -0.04392467],
       [-2.35907244,  1.36522446,  1.11932603],
       [ 0.78723793,  2.04111332, -0.91680328],
       [-1.5604315 ,  0.05827394, -0.40716146]])

In [65]:
import pandas as pd

In [66]:
pd.DataFrame(d)

0         1         2
0 -0.217782 -0.186511 -0.043925
1 -2.359072  1.365224  1.119326
2  0.787238  2.041113 -0.916803
3 -1.560432  0.058274 -0.407161

In [67]:
d1 = np.random.randn(2,3,4)

In [68]:
d1

array([[[-0.80073375, -1.56101881,  0.55499073, -0.61537558],
        [ 0.06604927, -0.31398945,  0.97333309, -0.63484458],
        [-0.29989601,  0.73886942, -0.70030437,  1.5780712 ]],

       [[-1.11868321,  0.62871599, -0.30126679, -1.68203247],
        [-1.36613527, -0.45408892, -1.88206339,  0.74423187],
        [ 0.27433721,  0.52178699,  1.93040732, -0.51245482]]])

In [71]:
#pd.DataFrame(d1) --> cannoot pass 3d array to dataframe which is 2D

In [74]:
d1 = d1.reshape(12,2)

In [75]:
pd.DataFrame(d1)

0         1
0  -0.800734 -1.561019
1   0.554991 -0.615376
2   0.066049 -0.313989
3   0.973333 -0.634845
4  -0.299896  0.738869
5  -0.700304  1.578071
6  -1.118683  0.628716
7  -0.301267 -1.682032
8  -1.366135 -0.454089
9  -1.882063  0.744232
10  0.274337  0.521787
11  1.930407 -0.512455

In [77]:
d1.reshape(8,-1) #-1 identifies the shape required

array([[-0.80073375, -1.56101881,  0.55499073],
       [-0.61537558,  0.06604927, -0.31398945],
       [ 0.97333309, -0.63484458, -0.29989601],
       [ 0.73886942, -0.70030437,  1.5780712 ],
       [-1.11868321,  0.62871599, -0.30126679],
       [-1.68203247, -1.36613527, -0.45408892],
       [-1.88206339,  0.74423187,  0.27433721],
       [ 0.52178699,  1.93040732, -0.51245482]])