In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3,10,2)) #range-->Only integers

[3, 5, 7, 9]

In [5]:
np.arange(0.5,10) #arange-->for floating numbers

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [6]:
np.arange(5,-4,-0.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [7]:
np.linspace(1,10,20,retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [8]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [15]:
np.ones((3,4,2)) * 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [16]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
a.shape

(5, 5)

In [19]:
a.size

25

In [20]:
a.ndim

2

In [21]:
a1 = np.random.randn(3,4)
a1

array([[-0.27616677, -0.48674643, -0.82612993, -0.02049491],
       [-0.24970875,  0.21508399, -0.85668397, -1.00770918],
       [ 2.0614034 , -1.68536966, -1.26696204, -1.61399261]])

In [22]:
a1[1][1]

0.21508399489386856

In [23]:
a1[0:2,0:2]

array([[-0.27616677, -0.48674643],
       [-0.24970875,  0.21508399]])

In [24]:
a1[[0,1],0:2]

array([[-0.27616677, -0.48674643],
       [-0.24970875,  0.21508399]])

In [25]:
a1

array([[-0.27616677, -0.48674643, -0.82612993, -0.02049491],
       [-0.24970875,  0.21508399, -0.85668397, -1.00770918],
       [ 2.0614034 , -1.68536966, -1.26696204, -1.61399261]])

In [26]:
a1[[1,2],3]

array([-1.00770918, -1.61399261])

In [32]:
m1 = np.random.randint(2,4,(3,3))

In [33]:
m2 = np.random.randint(3,5,(3,3))

In [34]:
m1

array([[3, 2, 2],
       [3, 3, 2],
       [2, 3, 2]])

In [35]:
m2

array([[4, 4, 3],
       [3, 4, 4],
       [4, 3, 3]])

In [36]:
m1*m2

array([[12,  8,  6],
       [ 9, 12,  8],
       [ 8,  9,  6]])

In [37]:
m1@m2 #-->matrix multiplication

array([[26, 26, 23],
       [29, 30, 27],
       [25, 26, 24]])

In [38]:
m1

array([[3, 2, 2],
       [3, 3, 2],
       [2, 3, 2]])

In [39]:
pow(m1,2)

array([[9, 4, 4],
       [9, 9, 4],
       [4, 9, 4]])

In [40]:
np.sqrt(m1)

array([[1.73205081, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.41421356],
       [1.41421356, 1.73205081, 1.41421356]])

In [42]:
np.log10(m1)

array([[0.47712125, 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   ],
       [0.30103   , 0.47712125, 0.30103   ]])

In [43]:
np.exp(m1)

array([[20.08553692,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692,  7.3890561 ],
       [ 7.3890561 , 20.08553692,  7.3890561 ]])

In [44]:
m1**2

array([[9, 4, 4],
       [9, 9, 4],
       [4, 9, 4]])